### ISSUE TITLE
Edit links broken after pagination change

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/ListerNativeDateFormat#2]
Hi @Toutouwai - sorry about the cryptic title :)

Basically what happens is if you have clicked on one of the page numbers to view results beyond the initial list and then click on the date format button, it reloads the page with `/page2` in the URL. This then get added to the edit links on each row, resulting in things like: /access/users/page6/edit/?id=26296 which obviously don't work.

I think it's just a matter of changing this line: https://github.com/Toutouwai/ListerNativeDateFormat/blob/master/ListerNativeDateFormat.module#L78

**Comment by Toutouwai** [comment]
Hi @adrianbj,

This should be fixed in v0.1.3.

But I actually think it should be addressed in the core so I opened a related issue: https://github.com/processwire/processwire-issues/issues/1781

**Comment by adrianbj** [comment]
Thanks @Toutouwai and also thanks for filing the related issue reports with Ryan.
